[package]
name = "rustcpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = { version = "2.7.5", features = [] }
pest_derive = "2.7.5"
